In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

df = pd.read_csv("pakistan_development_raw.csv")

df.head()

,Year,GDP Growth,GDP per Capita,Inflation,Unemployment,Population,Population Growth,Urban Population,Life Expectancy,Access to Electricity,Renewable Energy
0,1960,NaN,82.024100,6.947368,NaN,45709310,NaN,22.299698,44.101,NaN,NaN
1,1961,5.987346,87.777825,1.640420,NaN,46921277,2.616924,22.632127,44.956,NaN,NaN
2,1962,4.482859,89.503953,-0.516462,NaN,48156128,2.597716,22.934215,45.850,NaN,NaN
3,1963,8.688832,93.650873,1.456488,NaN,49447776,2.646868,23.208181,46.761,NaN,NaN
4,1964,7.569757,102.459764,4.179587,NaN,50799999,2.697925,23.460517,47.831,NaN,NaN

In [3]:
print("Dataset shape:", df.shape)

df.info()

Dataset shape: (66, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   66 non-null     int64
 1   GDP Growth             65 non-null     float64
 2   GDP per Capita         66 non-null     float64
 3   Inflation              66 non-null     float64
 4   Unemployment           35 non-null     float64
 5   Population             66 non-null     int64
 6   Population Growth      65 non-null     float64
 7   Urban Population       66 non-null     float64
 8   Life Expectancy        65 non-null     float64
 9   Access to Electricity  27 non-null     float64
 10  Renewable Energy       32 non-null     float64
dtypes: float64(9), int64(2)
memory usage: 5.8 KB

In [4]:
missing_values = df.isna().sum()

missing_values

Year                      0
GDP Growth                1
GDP per Capita            0
Inflation                 0
Unemployment             31
Population                0
Population Growth         1
Urban Population          0
Life Expectancy           1
Access to Electricity    39
Renewable Energy         34
dtype: int64

In [5]:
missing_percentage = (
    df.isna().mean() * 100
).sort_values(ascending=False)

missing_percentage

Access to Electricity    59.090909
Renewable Energy         51.515152
Unemployment             46.969697
Life Expectancy           1.515152
Population Growth         1.515152
GDP Growth                1.515152
Year                      0.000000
GDP per Capita            0.000000
Inflation                 0.000000
Population                0.000000
Urban Population          0.000000
dtype: float64

In [6]:
duplicate_rows = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 0

In [7]:
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

print(df["Year"].min())
print(df["Year"].max())

1960
2025

In [8]:
df["Year"].isna().sum()

np.int64(0)

In [9]:
descriptive_statistics = df.describe().T

descriptive_statistics

,count,mean,std,min,25%,50%,75%,max
Year,66.0,1.992500e+03,1.919635e+01,1.960000e+03,1.976250e+03,1.992500e+03,2.008750e+03,2.025000e+03
GDP Growth,65.0,4.936925e+00,2.494734e+00,-1.274087e+00,3.651350e+00,4.846581e+00,6.537487e+00,1.135346e+01
GDP per Capita,66.0,6.076009e+02,4.925394e+02,8.202410e+01,1.890642e+02,3.978166e+02,9.953937e+02,1.595909e+03
Inflation,66.0,8.564801e+00,5.935094e+00,-5.164622e-01,4.693587e+00,7.336123e+00,1.052698e+01,3.076813e+01
Unemployment,35.0,2.075857e+00,2.039830e+00,3.980000e-01,5.990000e-01,6.200000e-01,3.616500e+00,6.338000e+00
Population,66.0,1.344384e+08,6.630707e+07,4.570931e+07,7.219065e+07,1.252835e+08,1.931572e+08,2.552196e+08
Population Growth,65.0,2.645880e+00,6.616999e-01,1.302164e+00,2.382005e+00,2.767106e+00,2.989319e+00,4.178102e+00
Urban Population,66.0,3.086013e+01,4.825281e+00,2.229970e+01,2.678060e+01,3.134175e+01,3.458253e+01,3.952560e+01
Life Expectancy,65.0,5.901729e+01,6.182456e+00,4.410100e+01,5.506900e+01,5.998300e+01,6.400200e+01,6.779900e+01
Access to Electricity,27.0,8.511205e+01,8.655884e+00,7.026535e+01,7.755000e+01,8.780000e+01,9.305000e+01,9.570000e+01
Renewable Energy,32.0,4.892813e+01,4.358102e+00,4.160000e+01,4.627500e+01,4.795000e+01,5.167500e+01,5.810000e+01

In [10]:
descriptive_statistics.to_csv("descriptive_statistics.csv", index=True)

print("Descriptive statistics saved.")

Descriptive statistics saved.

In [11]:
# Save the cleaned dataset
df.to_csv("pakistan_development_processed.csv", index=False)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

In [12]:
print("Final dataset shape:", df.shape)
df.head()

Final dataset shape: (66, 11)

,Year,GDP Growth,GDP per Capita,Inflation,Unemployment,Population,Population Growth,Urban Population,Life Expectancy,Access to Electricity,Renewable Energy
0,1960,NaN,82.024100,6.947368,NaN,45709310,NaN,22.299698,44.101,NaN,NaN
1,1961,5.987346,87.777825,1.640420,NaN,46921277,2.616924,22.632127,44.956,NaN,NaN
2,1962,4.482859,89.503953,-0.516462,NaN,48156128,2.597716,22.934215,45.850,NaN,NaN
3,1963,8.688832,93.650873,1.456488,NaN,49447776,2.646868,23.208181,46.761,NaN,NaN
4,1964,7.569757,102.459764,4.179587,NaN,50799999,2.697925,23.460517,47.831,NaN,NaN